version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: workforce-backend-local:latest
    container_name: workforce-backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=workforce_user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=workforcerhms@gmail.com
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - APP_CORS_ALLOWED_ORIGINS=http://workforce-hrms-frontend-vamsi.s3-website.ap-south-1.amazonaws.com
      - SPRING_DATASOURCE_URL=jdbc:mysql://workforce-mysql:3306/workforce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      workforce-mysql:
        condition: service_healthy

  workforce-mysql:
    image: mysql:8.0
    container_name: workforce-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=workforce_db
      - MYSQL_USER=workforce_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data:
